// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// inmp441_pio //
// ----------- //

#define inmp441_pio_wrap_target 0
#define inmp441_pio_wrap 11

#define inmp441_pio_max_clock_rate 3200000

static const uint16_t inmp441_pio_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop                    side 0     
    0xa842, //  1: nop                    side 1     
    0xe038, //  2: set    x, 24           side 0     
    0x4801, //  3: in     pins, 1         side 1     
    0x0043, //  4: jmp    x--, 3          side 0     
    0xe826, //  5: set    x, 6            side 1     
    0xa042, //  6: nop                    side 0     
    0x0846, //  7: jmp    x--, 6          side 1     
    0xf03f, //  8: set    x, 31           side 2     
    0xb842, //  9: nop                    side 3     
    0x1049, // 10: jmp    x--, 9          side 2     
    0xb842, // 11: nop                    side 3     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program inmp441_pio_program = {
    .instructions = inmp441_pio_program_instructions,
    .length = 12,
    .origin = -1,
};

static inline pio_sm_config inmp441_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + inmp441_pio_wrap_target, offset + inmp441_pio_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

#include "hardware/clocks.h"
static inline void inmp441_pio_program_init(PIO pio, uint sm, uint offset, uint ctrl_pin_start, uint data_pin) {
    pio_gpio_init(pio, ctrl_pin_start);
    pio_sm_set_consecutive_pindirs(pio, sm, ctrl_pin_start, 2, true);
    pio_sm_config c = inmp441_pio_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, ctrl_pin_start);
    sm_config_set_set_pins(&c, data_pin, 1);
    sm_config_set_in_shift(&c, false, true, 24);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_NONE);
    float div = clock_get_hz(clk_sys) / inmp441_pio_max_clock_rate;
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void inmp441_pio_program_deinit(PIO pio, uint sm) {
    pio_sm_set_enabled(pio, sm, false);
    pio_sm_unclaim(pio, sm);
}

#endif

